### ISSUE TITLE
Trying to install in xfce in crouton

### ISSUE THREAD

**Issue by Roaders** [GalliumOS/galliumos-samus#1]
Hi

I am very new to Linux so I have really no idea if this is possible (sorry for wasting time if it's not).

I have installed GalliumOs on my Chromebook pixel and love it but much prefer the convenience of using crouton and running a version of Linux inside chromeOs. I much prefer the look and adaptations that have been made to gallium for the pixel so I would like to make the version of linux that I am running be as similar to Gallium as I can - particularly the hidpi settings.

I have tried to run `sudo apt-get install galliumos-samus` but I get the error `E: Unable to locate package galliumos-samus`. I understand that I can add new repos to apt-get so what is the repo that I need to use for `galliumos-samus` and is this likely to work on my Linux install.

I am running trusty with xfce4 (I think).

Many thanks - and Happy Christmas :-)

**Comment by reynhout** [comment]
It's not possible to bring all of the GalliumOS customizations into a Crouton environment. The ChromeOS kernel is 3.19, and GalliumOS uses 4.7.2 or later.

For the HiDPI config, it might work to copy the contents of https://github.com/GalliumOS/galliumos-hidpi/tree/master/etc/skel/.config into your `/etc/skel/.config` directory, and then into your `$HOME/.config` as well.

If that doesn't work, post a follow up question on https://reddit.com/r/GalliumOS. Thanks, and good luck.

**Comment by reynhout** [comment]
You could also add the GalliumOS package repository, but that's more likely to cause trouble than not. Our packages are made for a much newer version of Linux than ChromeOS, and we've never tested the effects. There are clever configs where you can only get the `galliumos-hidpi` package from the GalliumOS repo, but the likelihood of conflicts remain. I'd recommend just copying the files.

**Comment by Roaders** [comment]
OK, many thanks. I'll give that a try.
